import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Navbar from "@/components/Navbar/Navbar";
import HomeSection from "@/components/Home/HomeSection";
import AboutSection from "@/components/About/AboutSection";

export default function Home() {
  return (
    <>
      <Head>
        <title>77</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{ padding: "0 3.125rem" }}>
        <Navbar />
        <HomeSection />
        <AboutSection/>
      </main>
    </>
  );
}
